EXP:
    ID: MITIndoor67
    OUTPUT_DIR: Results

DATASET:
    NAME: MITIndoor67
    ROOT: ./Data/Datasets/
    SCENE_LABELS: ./Data/Datasets/MITIndoor67/scene_names.txt
    SEM_LABELS: ./Data/Datasets/ADEChallengeData2016/objectInfo150.txt
    N_CLASSES_SCENE: 10
    N_CLASSES_SEM: 151

DATALOADER:
    NUM_WORKERS: 0

MODEL:
    ARCH: ResNet-50
    PATH: ./Data/Model Zoo/MITIndoor67/
    NAME: SAScene_ResNet50_MIT
    ONLY_RGB: FALSE
    ONLY_SEM: FALSE
    SAVE_PATH: ./MODEL/

TRAINING:
    PRINT_FREQ: 10
    PRECOMPUTED_SEM: TRUE
    BATCH_SIZE:
        TRAIN: 10
        TEST: 10
    LR: 2.5e-4
    LR_DECAY: 10
    MOMENTUM: 0.9
    OPTIMIZER: DFW
    POLY_POWER: 0.9
    WEIGHT_DECAY: 5.0e-4
    AVERAGE_LOSS: 20
    EPOCHS: 100

VALIDATION:
    PRINT_FREQ: 134
    BATCH_SIZE:
        TRAIN: 10
        TEST: 10
    TEN_CROPS: FALSE

TEST:
    PRINT_FREQ: 134
    BATCH_SIZE:
        TRAIN: 10
        TEST: 10
    TEN_CROPS: FALSE